FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["StockRanker.Ui/StockRanker.Ui.csproj", "StockRanker.Ui/"]

RUN dotnet restore "StockRanker.Ui/StockRanker.Ui.csproj"

COPY . .
RUN dotnet publish "StockRanker.Ui/StockRanker.Ui.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "StockRanker.Ui.dll"]
