<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>stockranker-api-8e0bda12-07d8-45ff-8d1f-1670a705f32a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockRanker.Application\StockRanker.Application.csproj" />
    <ProjectReference Include="..\StockRanker.Infrastructure\StockRanker.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="data\stocks.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
